### ISSUE TITLE
Can't compile app with OBSERVER as an only role

### ISSUE THREAD

**Issue by KKopyscinski** [apache/mynewt-nimble#914]
Compiling app with config:
```yml
syscfg.vals:
    BLE_ROLE_BROADCASTER: 0
    BLE_ROLE_CENTRAL: 0
    BLE_ROLE_OBSERVER: 1
    BLE_ROLE_PERIPHERAL: 0
```
returns following compilation errors:
-`implicit declaration of function 'ble_gap_master_extract_state'`
-`implicit declaration of function 'ble_gap_has_client';`
-`implicit declaration of function 'ble_gap_master_connect_failure'`
-`implicit declaration of function 'ble_gap_master_reset_state'`
-` 'ble_gap_adv_finished' defined but not used`
